Blog/urls.py
from django.conf.urls import url
from Blog import views

app_name = 'Blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^detail/(?P<artical_id>\d+)/$',views.ArticalDetail.as_view(),name='detail'),
    url(r'^tags/(?P<tag_id>\d+)/$',views.TagView.as_view(),name='tag'),
    url(r'^detail/(?P<artical_id>\d+)/comment/$',views.CommentView, name='comment')

]

Site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Blog import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('Blog.urls')),
]

Blog/models.py
from django.db import models

# Create your models here.
class Artical(models.Model):
    STATUS = (
        ('D','Draft'),
        ('P','Published')
    )
    title = models.CharField('标题',max_length=50)
    body = models.TextField('正文')
    create_time = models.DateTimeField(auto_now_add=True)
    last_modified_time = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS,default='D',max_length=1)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    topped = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag',verbose_name='标签',null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']


class Tag(models.Model):
    name = models.CharField('标签',max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)
    last_modified_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user_name = models.CharField('评论者名字',max_length=10)
    body = models.TextField('评论内容')
    create_time = models.DateTimeField(auto_now_add=True)
    artical = models.ForeignKey('Artical',on_delete=models.CASCADE)

    def __str__(self):
        return self.body[:20]

Blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model =Comment
        fields = ['user_name','body']
        widgets = {
            'user_name': forms.TextInput(attrs={
                'class': 'nickname form-control',
                'placeholder':'nickname',

            }),
            'body':forms.Textarea(attrs={
                'class':'from-control size-control',
                'placeholder':'评论内容',
                'rows':4
            }),
        }

Blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Artical,Tag,Comment
from .forms import CommentForm
import mistune
from django.views.generic.list import ListView
from django.views.generic import DetailView
import markdown2



# Create your views here.

class IndexView(ListView):



    template_name = 'Blog/T.html'
    context_object_name = 'artical_list'

    def get_queryset(self):
        artical_list = Artical.objects.filter(status = 'P')
        for artical in artical_list:
            artical.body = mistune.markdown(artical.body, extras=['fenced-code-blocks'])

        return artical_list

    def get_context_data(self, **kwargs):
        # 增加额外的数据，这里返回一个文章分类，以字典的形式
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)

class ArticalDetail(DetailView):
    model = Artical
    template_name = 'Blog/detail.html'
    context_object_name = 'artical'
    pk_url_kwarg = 'artical_id'


    def get_object(self, queryset=None):
        obj = super(ArticalDetail, self).get_object()
        obj.views += 1
        obj.save()
        obj.body = mistune.markdown(obj.body,extras=['fenced-code-blocks'])
        return obj

    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.comment_set.all()
        kwargs['form'] = CommentForm()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(ArticalDetail, self).get_context_data(**kwargs)

class TagView(ListView):
    template_name = 'Blog/T.html'
    context_object_name = 'artical_list'

    def get_queryset(self):
        artical_list = Artical.objects.filter(tags = self.kwargs['tag_id'], status = 'P')
        for artical in artical_list:
            artical.body = mistune.markdown(artical.body,extras=['fenced-code-blocks'],)
        return artical_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['tag_name'] = get_object_or_404(Tag, pk = self.kwargs['tag_id'])
        return super(TagView, self).get_context_data(**kwargs)


def CommentView(request,artical_id):
    if request.method == 'POST':
        form =CommentForm(request.POST)
    if form.is_valid():
        name = form.cleaned_data['user_name']
        body = form.cleaned_data['body']

        artical = get_object_or_404(Artical, pk=artical_id)
        new_record = Comment(user_name=name,
                                 body=body,
                                 artical=artical)
        new_record.save()
        return redirect('Blog:detail', artical_id)

Blog/templates/Blog/T.html
{% extends 'Blog/base.html' %}
{% load staticfiles %}
{% block link %}
<link rel="stylesheet" href="{% static 'Blog/css/T.css' %}">
{% endblock %}

{% block title %}
Blog
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="row">

            <div class="col-xs-12 col-md-8 ">
                {% load paginate_tags %}
                {% paginate artical_list 3 %}
                {% for artical in artical_list %}
                <div class=" box">
                    <a href="{% url 'Blog:detail' artical.id %}"> <div class="well-sm">
                                <h2 class="text-center">{{ artical.title }} </h2></div></a>
                                
                    <hr>
                                <div class="row">
                                    <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">{{ artical.body | truncatechars:181 |safe  }}</div>
                                </div>

                                <br>

                                <div class="row">
                                    <div class="col-xs-6 gly-left">
                                        <i class="fa fa-eye"></i>Views: {{ artical.views }} 
                                    </div>
                                    <a href="{% url 'Blog:detail' artical.id %}">
                                        <div class="col-xs-6 text-right">
                                            <span class=" gly-right "> Read More <i class="fa fa-paper-plane"></i> </span>
                                        </div>
                                    </a>
                                </div>
                            
                        
                </div> 
                {% endfor %}

                <div>{% include 'Blog/pagination.html' %}</div>



            </div>

            <div class="col-xs-12 col-md-4">
                {% include "Blog/category.html" %}
            </div>

        </div>
    </div>
{% endblock content %}

Blog/templates/Blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="shortcut icon" href="{% static 'Blog/favicon.ico' %}">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'Blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'Blog/css/monokai_sublime.min.css' %}">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'Blog/css/DUO.css' %}">
	{% block link %}{% endblock %}
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
    	<div class="row">
      		<a href="{% url 'Blog:index' %}"><div class="col-xs-3 "><h2><span class="D">D</span><span class="U">U</span><span class="O">O</span></h2></div></a>
    	</div>
  	</div>
	
	{% block content %}{% endblock content %}


	<script src="{% static 'Blog/js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Blog/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Blog/js/highlight.min.js' %}" type="text/javascript"></script>
	<script >hljs.initHighlightingOnLoad();</script>
</body>
</html>

Blog/templates/Blog/category.html
<div class="well">
    <h4><i class="fa fa-tasks"></i> 标签云</h4>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped">
                {% for tag in tag_list %}
                <tr><td><i class="fa fa-tag"></i><a class="tags" href="{% url 'Blog:tag' tag.pk %}">{{ tag.name }}</a></td></tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

Blog/templates/Blog/comment.html
<div class="row">
	<div class="col-xs-12">
		<h4 class="lead">Comment</h4>
		<form method='post' action="{% url 'Blog:comment' artical.pk %}">
			{% csrf_token %}
			{% for field in form %}
				{{ field }}
				{{ field.errors }}
				<br>
			{% endfor %}
			<button type="submit" class="btn btn-info">评论</button>
		</form>
		
		<hr>

		{% for comment in comment_list %}
		<div class="box">
			<div class="row">
				<div class="col-xs-6   lead">{{ comment.user_name }}</div>
				<div class="col-xs-6 text-right text-muted">{{ comment.create_time }}</div>
			</div>
			<div class="lead">{{ comment.body }}</div>
			<hr>
			<a href="#" class="btn btn-info" title="不用点了，我不会做回复功能.">回复</a>
		</div>
		{% endfor %}
	</div>
</div>

Blog/templates/Blog/detail.html
{% extends 'Blog/base.html' %}
{% load staticfiles %}
{% block link %}
<link rel="stylesheet" href="{% static 'Blog/css/detail.css' %}">
{% endblock %}

{% block title %}
	{{ artical.title }}
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<h1>{{ artical.title }}</h1>
			<hr>
			<div class="row">
				
					<div class="col-xs-6 small"><i class="fa fa-eye"></i>Views: {{ artical.views }} </div>
					<div class="col-xs-6 small text-right"><i class="fa fa-calendar-minus-o"></i> {{ artical.create_time }} </div>
				
			</div>
			{{ artical.body | safe }}
			<br><br><br>

			{% include 'Blog/comment.html' %}
		</div>

		<div class="col-xs-12 col-md-4">
			{% include 'Blog/category.html' %}
		</div>
	</div>
</div>

{% endblock %}

Blog/templates/Blog/pagination.html
<ul class='pagination pagination-lg'>
    {% if artical_list.has_previous %}
        <li><a href="?page={{ artical_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li><a class="'disabled">&laquo;</a></li>
    {% endif %}


    {% for page in pages %}
        <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endfor %}

    {% if artical_list.has_next %}
        <li><a href="?page={{ artical_list.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li><a class="'disabled">&raquo;</a></li>
    {% endif %}
</ul>